language: python
sudo: false
python:
  - "pypy-5.4"
  - "pypy3.3-5.2-alpha1"
  - "nightly"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
matrix:
  allow_failures:
    - python: nightly
  include:
    - python: "3.6"
      env: TOXENV=check

install: pip install coveralls tox tox-travis
script: tox
after_success: coveralls
cache: pip
