language: python
sudo: false
python:
  - "pypy"
  - "pypy3"
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
install:
  - pip install -U pytest
  # Coveralls 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
  - pip install coveralls
  - pip install pytest-cov
script:
  py.test -v --assert=plain --tb=native  --cov tinydb
after_success:
  coveralls
