[tool.poetry]
name = "tinydb"
version = "4.0.0"
description = "TinyDB is a tiny, document oriented database optimized for your happiness :)"
authors = ["Markus Siemens <markus@m-siemens.de>"]
license = "MIT"

readme = "README.rst"

homepage = "https://github.com/msiemens/tinydb"
documentation = "https://tinydb.readthedocs.org/"

keywords = ["database", "nosql"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Topic :: Database",
    "Topic :: Database :: Database Engines/Servers",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Operating System :: OS Independent",
]

packages = [
    { include = "tinydb" }
]

[tool.poetry.urls]
"Changelog" = "https://github.com/msiemens/tinydb/en/latest/changelog.html"
"Issues" = "https://github.com/msiemens/tinydb/issues"

[tool.poetry.dependencies]
python = "^3.5"
coveralls = {version = "^1.8.2", optional = true}
pytest-azurepipelines = {version = "^0.8.0", optional = true}
pyyaml = {version = "^5.1.2", optional = true}
pytest-mypy = {version = "^0.4.1", optional = true, extras = ["ci"]}

[tool.poetry.dev-dependencies]
pytest = "^5.2.2"
pytest-codestyle = "^1.4.0"
pytest-cov = "^2.8.1"
pycodestyle = "^2.5.0"

[tool.poetry.extras]
ci = ["pyyaml", "pytest-azurepipelines", "coveralls"]

[build-system]
requires = ["poetry>=0.12", "pytest-runner~=5.2"]
build-backend = "poetry.masonry.api"
